# Generated by Django 3.0.7 on 2020-06-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=10)),
                ('dob', models.DateField(max_length=8)),
                ('contact', models.CharField(max_length=10)),
                ('joining_date', models.DateField(max_length=8)),
            ],
        ),
    ]
